spring:
  config:
    activate:
      on-profile: main

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:mariadb://${MAIN_DB_HOST}:${MAIN_DB_PORT}/${MAIN_DB_NAME}
    username: ${MAIN_DB_USER}
    password: ${MAIN_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  security:
    client:
      landing-page-url: ${LANDING_PAGE_URL}
      sign-up-page-url: ${SIGNUP_PAGE_URL}

server:
  domain: ${BACK_DOMAIN}
  port: 8080
  port-export: ${DEPLOY_SERVER_PORT:443}
  tomcat:
    threads:
      max: 100
      min-spare: 5
    accept-count: 50
#  ssl:
#    key-store: ${SSL_KEY_STORE}
#    key-store-type: ${SSL_KEY_TYPE}
#    key-store-password: ${SSL_KEY_PASSWORD}