spring:
  config:
    activate:
      on-profile: deploy

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:mariadb://${DEPLOY_DB_HOST}:${DEPLOY_DB_PORT}/${DEPLOY_DB_NAME}
    username: ${DEPLOY_DB_USER}
    password: ${DEPLOY_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  security:
    client:
      landing-page-url: ${LANDING_PAGE_URL}
      sign-up-page-url: ${SIGNUP_PAGE_URL}

#server:
#  domain: ${BACK_DOMAIN}
#  port: ${DEPLOY_SERVER_PORT:443}
#  ssl:
#    key-store: ${SSL_KEY_STORE}
#    key-store-type: ${SSL_KEY_TYPE}
#    key-store-password: ${SSL_KEY_PASSWORD}