spring:
  config:
    activate:
      on-profile: test

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:mariadb://${TEST_DB_HOST}:${TEST_DB_PORT}/${TEST_DB_NAME}
    username: ${TEST_DB_USER}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  security:
    client:
      landing-page-url: ${TEST_LANDING_PAGE_URL}
      sign-up-page-url: ${TEST_SIGNUP_PAGE_URL}

server:
  domain: ${BACK_DOMAIN}
  port: 8080
  port-export: ${DEV_SERVER_PORT:8443}
#  ssl:
#    key-store: ${SSL_KEY_STORE}
#    key-store-type: ${SSL_KEY_TYPE}
#    key-store-password: ${SSL_KEY_PASSWORD}

logging:
  level:
    root: DEBUG